### ISSUE TITLE
wrong info on walletServer while pool mining

### ISSUE THREAD

**Issue by de-luxe** [de-luxe/burstcoin-jminer#10]
'Winner feature disabled, property 'walletServer' undefined!' always shwn on poolMining, even if specified.

**Comment by ThorvaldAagaard** [comment]
Using burstcoin-jminer-0.4.4-SNAPSHOT>java -jar -d64 -XX:+UseG1GC burstcoin-jminer-0.4.4-SNAPSHOT.jar
I still get this message during initialization of miner

**Comment by de-luxe** [comment]
thanks, i reopen the issue ... will check that.
should not effect mining ... it is just confusing for user.
