### ISSUE TITLE
Excess verbage

### ISSUE THREAD

**Issue by QuintLeo** [de-luxe/burstcoin-jminer#32]
Way too much of the verbage displayed by this miner is totally worthless to folks using it - pretty much everything between the time/date and the : (colon) is just wasted characters that make this miner a royal PAIN TO USE on machines that do not have a incredibly wide display.
 I also believe the time and date stamping is way excessive and also just makes the display excessively wide.

**Comment by de-luxe** [comment]
Thanks for your suggestion ... it is the default logging of spring boot ...
https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-logging.html#boot-features-logging-format 
Never thought about adjusting it ... but i keep it in mind and maybe provide a property to minimize it.
For now you could just move the info you do not want to see left out of the visible area of your display.

**Comment by QuintLeo** [comment]
I would suggest turning the middle part of the text off when debug=off, and back on when debug=on, at it seems to be debug-related info.
The date and time stamping isn't as bad, I can see that being usefull for "is this thing running" determination.

 Another option that would take a significant amount of work would be to move to a Blago Miner style display, or better yet a ccminer-type console display.

 Any idea when you will get the chance to impliment "more than one OpenCL device" functionality? Perhaps on a "one device per drive" basis, if that's easier/quicker to set up?

--------------------------------------------
On Sat, 5/27/17, luxe <notifications@github.com> wrote:

 Subject: Re: [de-luxe/burstcoin-jminer] Excess verbage (#32)
 To: "de-luxe/burstcoin-jminer" <burstcoin-jminer@noreply.github.com>
 Cc: "QuintLeo" <LeonisSmith@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Saturday, May 27, 2017, 3:23 PM
 
 Thanks for your suggestion ... it
 is the default logging of spring boot ...
 
 https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-logging.html#boot-features-logging-format
 
 Never thought about adjusting it ... but i keep it in mind
 and maybe provide a property to minimize it.
 
 For now you could just move the info you do not want to see
 left out of the visible area of your display.
 
 —
 You are
 receiving this because you authored the thread.
 Reply
 to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by de-luxe** [comment]
Binding a reduced log to debug flag is a good idea.

I never focused a lot on appearance in command line, always had a gui in mind, but not started it yet.
Surely something i still have in mind for the future ... kind of making mining more entertaining.

Is there really a need for more than one GPU ... we will soon have a e.g. VEGA GPU that should able to compute a PB of plots within a minute. Also it is possible to run a 2nd instance of jminer if there is such a need ... for now i'm not planning on implement multi GPU support due to the above.

**Comment by QuintLeo** [comment]
On one of my current machines, I've got an 8-core AMD FX and a HD 7750, neither of which can saturate drive reads but I think the combination would.
I also have a lot of machines with AMD A10 APUs - where neither the GPU nor the CPU come close to saturating drive read speed but the combination might get close..

 Even on my SMALL drive setups I see blocks where the reads take longer than some blocks take and I lose out on potential deadlines found.

 Some folks have many-drive machines (I don't yet) in the 100+ TB capacity range and would probably appreciate being able to get ALL of their plot drives read faster to reduce lost deadline count.

I've been contemplating the idea of building up an older Backblaze "pod" and stuffing (over time) 45 of the Seagate Archive 8TB drives in it - that would DEFINITELY need a lot of horsepower on multiple cards to read 360GB of drives in a reasonable amount of time.

2 or more mid-range GPU would be better than a single big one, unless you can figure out how to have one card process plots from multiple drives at the same time, as the bigger cards easily saturate max sustained HD read speed from a single card then a large part of their capacity goes to waste.

 Running multiple instances should help on multi-drive setups, point each instance at it's own GPU / CPU and then split the drives up between them. When I get a multi-drive machine built I'll definitely try that.
 It doesn't help folks with lower-end GPU + CPU setups and one drive though.

--------------------------------------------
On Sun, 5/28/17, luxe <notifications@github.com> wrote:

 Subject: Re: [de-luxe/burstcoin-jminer] Excess verbage (#32)
 To: "de-luxe/burstcoin-jminer" <burstcoin-jminer@noreply.github.com>
 Cc: "QuintLeo" <LeonisSmith@yahoo.com>, "Author" <author@noreply.github.com>
 Date: Sunday, May 28, 2017, 4:54 AM
 
 Binding a reduced log to debug
 flag is a good idea.
 I never focused a lot on appearance in command line,
 always had a gui in mind, but not started it yet.
 
 Surely something i still have in mind for the future ...
 kind of making mining more entertaining.
 Is there really a need for more than one GPU ... we will
 soon have a e.g. VEGA GPU that should able to compute a PB
 of plots within a minute. Also it is possible to run a 2nd
 instance of jminer if there is such a need ... for now
 i'm not planning on implement multi GPU support due to
 the above.
 
 —
 You are
 receiving this because you authored the thread.
 Reply
 to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by de-luxe** [comment]
Mining speed not only depends on provided GPU computing power, but mainly on how drives are attached, even if i understand that there could be a need for multiple openCL devices, i have to admit that if someone can effort 100TB+ for mining, it should also be possible to get a decent GPU in addition. 

Just a example ...  lets say you use 40 x 8TB drives, thats 320TB and can be handled by a 280x GPU within 30sec. Thats ~8000€ for drives and ~150€ for GPU ... and a 2nd GPU would not increase speed, as drives can not read needed data faster anyway.

But if it comes to the point, that i rewrite the core parts of the miner i will consider enable multiple openCL devices. I just do not see a high prio here ... 

Currently a workaround would be running two instances of jminer, every instance with own GPU.
