### ISSUE TITLE
Multiline configuration

### ISSUE THREAD

**Issue by akrobet** [de-luxe/burstcoin-jminer#37]
Is it possible somehow to split the plotPaths parameter into multiple drives? I have more than 20 drives and it's a bit cumbersome to edit.

**Comment by de-luxe** [comment]
@akrobet You can use multiline like:
```
plotPaths=\
C:/data/burst#00,\
C:/data/burst#01,\
C:/data/burst#02,\
C:/data/burst#03,\
C:/data/burst#04,\
C:/data/burst#05
```
