### ISSUE TITLE
Properties Resetting 

### ISSUE THREAD

**Issue by miekshreds** [de-luxe/burstcoin-jminer#38]
Every time I change anything in the properties file and save it resets the file to what the original file was. Do I have to change the original file(PROPERTIES_ORIGINAL...) to get it to save my changes to the non-original file?

**Comment by de-luxe** [comment]
This is surely not done by jminer itself ... but maybe by AOI client ... only solution i can think of is to not use AOI ...
You have to choose ... let AOI control your setting or do it by hand and do not use AOI to start jminer ...
