### ISSUE TITLE
PROBLEM WITH THIS WHEN MINING

### ISSUE THREAD

**Issue by canopussy** [de-luxe/burstcoin-jminer#39]
Hello,
any help with this bugs? im using Java_Runtime_Environment_(64bit)_v8_Update_131 and jminer 0.4.11...appreciate it ... much thx
![2017-07-28 08_07_08-c__windows_system32_cmd exe](https://user-images.githubusercontent.com/30524160/28712361-335f3136-738b-11e7-8b07-55540d5bea5c.png)

**Comment by de-luxe** [comment]
@canopussy Thats not a bug, you have set 'debug=true' in your jminer.properties, without there would have been just a info, that the miner failed to get miningInfo from pool ... per default the miner asks ever 2 sec. for it and if it fails from time to time it is not a big deal. Btw. i also notice new Issues post if their title is not in caps.

**Comment by canopussy** [comment]
aha,i see chief= i have setup from other pool and yes,debug is =true .. pool.burstcoin.sk is down and i jumped to burst.ninja

when i set it to false=my mining will be bad? thanks
i have bad feeling from this,sometimes i not mine 1-2 hours :(

**Comment by de-luxe** [comment]
@canopussy debug=false has no influence on mining, just on whats logged/ displayed in the command line window.

You can check for block height that should be currently mined:
http://burst.btfg.space:81/network
http://status.burstcontrol.com:7777/network
If the miner is behind, there may be a issue with your current pool.
