### ISSUE TITLE
Showing Zero capacity

### ISSUE THREAD

**Issue by amity203** [de-luxe/burstcoin-jminer#41]
When I run CPU mining directly from wallet, it show all my drives and full capacity is scanned.
When I run Jminer with AMD rx 580 GPU, it just showing 2 drive and not rest of the drives. When I remove these 2 drives from list it end up showing zero drives. I do not see any plotting issue as CPU miner is still able to recognize all drives? Any known issue related to this?

**Comment by de-luxe** [comment]
Maybe you need to edit jminer.properties yourself and start miner manually and not from AIO.

**Comment by amity203** [comment]
Yeah for GPU, i am starting manually still this issue is happening. Not sure what could be wrong with jminer.properties because if it is recognizing 2 drives, it should recognize other drives as well. see properties file content as below:
plotPaths=J:/Burst/plots,I:/Burst/plots,H:/Burst/plots,F:/Burst/plots,K:/Burst/plots
poolMining=true
numericAccountId=2625230493374575435
poolServer=http://pool.burstcoin.ml:8124
walletServer=http://localhost:8125
passPhrase=xxxxxxxxxxxxxx
platformId=1
deviceId=4
chunkPartNonces=960000
 listPlotFiles=true
refreshInterval=2000
writeLogFile=true
showDriveInfo=true
connectionTimeout=30000

**Comment by amity203** [comment]
you can close this, it is plotting mistake as numeric id was something else, just renamed the files with correct numeric id and its showing full capacity now, hope changing numeric id in the file name should not cause any problem.

**Comment by de-luxe** [comment]
@amity203 You can not rename, you need to replot ... chaning accoinId in plotfilename will result in invalid plotfiles. Plots are generated for given account.
