### ISSUE TITLE
Failled to parse response from server.

### ISSUE THREAD

**Issue by mountassir** [de-luxe/burstcoin-jminer#45]
Getting few of these errors in version 0.4.11 while mining on pool **http://pool.burstcoin.ro/**, any idea how critical these are?

`2017-10-16 19:47:01.717  INFO 1382 --- [    roundPool-1] burstcoin.jminer.JMinerCommandLine       : dl '795870' send (pool) [nonce '55004397']`

`2017-10-16 19:47:01.942  WARN 1382 --- [askExecutor-275] b.j.c.n.task.NetworkSubmitPoolNonceTask  : Error: On submit nonce to pool, could not parse response: '{ "result" : "success", "deadline" : 60218566784215, "deadlineText" : "1,936,039y 3m 22d 14:16:55" }'`

`2017-10-16 19:47:01.944  INFO 1382 --- [askExecutor-275] burstcoin.jminer.JMinerCommandLine       : dl '795870' NOT confirmed!  [ 9d 5h 4m 30s ]`

**Comment by de-luxe** [comment]
Should not be critical in general, the pool sent a response that the miner was not prepared for and therefore could not handle (parse) it ... but your deadline was submitted successful, due "result" : "success".
However thanks for opening a ticket, so i can fix that in future releases. 
Meanwhile i suggest using another pool or miner to have a better mining experience.

**Comment by de-luxe** [comment]
Just checked the code, the miner is expecting 'deadlineString' and not 'deadlineText' like http://pool.burstcoin.ro sent. Currently no idea why that has changed.

Edit: Also the submitted dl 795870 does not match the response dl 60218566784215 ... if the miner works in general and this problem only occures from time to time you may just ignore it.

**Comment by chrulri** [comment]
You could use [@JsonAlias](https://github.com/FasterXML/jackson-annotations/blob/master/src/main/java/com/fasterxml/jackson/annotation/JsonAlias.java) on `SubmitResultResponse.deadlineString` so it could support both 'deadlineString' and 'deadlineText'.

**Comment by Creepsky** [comment]
Sorry, this is most likely because of the creepMiner (pool.burstcoin.ro is using a creepMiner in front of the pool). I added both now, "deadlineText" and "deadlineString".

**Comment by MarkPerkins** [comment]
@Creepsky http://fastpool.info returns just "deadline" 
`{"debug": {"baseTarget": {omitted}, "url": "{omitted}", "time": "{omitted}"}, "deadline": 30803157, "requestProcessingTime": 188, "result": "success"}`

**Comment by pvanmastrigt** [comment]
Hi, this issue would appear to still be around - I use an iMac (2017) with jminer 0.4.12 for pool mining on fastpool.info and this error is persistent. Although it does not stop the mining, the log file gets very big and I worry that the efficiency is also affected. Any clear resolution appreciated,

**Comment by de-luxe** [comment]
@pvanmastrigt please post the error from your logs, so i can ensure it is a parse  issue and not a connection one. Thanks.

**Comment by pvanmastrigt** [comment]
Hello - as per your advice (other thread) - tried a different pool and no more problems thanks.

With regards
Piet
