### ISSUE TITLE
Help with configuring jminer on Raid 0 drive

### ISSUE THREAD

**Issue by PawelL01** [de-luxe/burstcoin-jminer#48]
Hi Guys,

I hope you could help to solve the problem of jminer not working on Raid 0 configured drive. It is 2 drive setup (6TB) 3TB plotted. Do you have any suggestion how jminer.properties should be configured to mine Burstcoin
Would be very grateful for advice.

Cheers

**Comment by de-luxe** [comment]
@PawelL01 Treat the Raid created drive like a normal one in jminer, should make no difference. However it is better for mining speed and for your drives to NOT USE RAID but just 2 single drives. With raid they will be read one after the other and not in parallel.

**Comment by PawelL01** [comment]
@de-luxe Many thanks, I thought so. Just plotting one small drive to try it out. I've run to many problems with this Raid 0 configuration and was using it because I had a spare space available on this drive.  I am consistently getting the message that jminer "Unable to get mining info from wallet."
