### ISSUE TITLE
intel gpu

### ISSUE THREAD

**Issue by sifourquier** [de-luxe/burstcoin-jminer#50]
Hi i have a pc with a intel gpu opencl work (try with pascal mining on sgminer is slow but he work) 
is possible to use intel gpu?

[open cl error.log](https://github.com/de-luxe/burstcoin-jminer/files/1628255/open.cl.error.log)

**Comment by de-luxe** [comment]
@sifourquier Should be possible, you may need to install intel opencl sdk ...
http://jocl.org/
https://software.intel.com/en-us/intel-opencl

**Comment by Smit1237** [comment]
Works very well  under linux with custom intel kernel, opencl 2.0.

**Comment by AirBorne04** [comment]
works fine for me in windows too
