### ISSUE TITLE
targetDeadline only used in solo mining mode

### ISSUE THREAD

**Issue by AirBorne04** [de-luxe/burstcoin-jminer#52]
Hi,

First of all your miner is great!

i am pool mining and realized that the targetDeadline is only respected in solo mining mode. I was wondering why that is, due to the fact that other miners take the minimum of the configured and the pool mining deadlines. That seems to make sense for me. In my case the pool has a rather high deadline of a year, but my deadlines are usually max 3 months so i would disregard all the others. Of course i could change the pool but would feel more flexible if i could just change my targetDeadline.

Thank you

**Comment by de-luxe** [comment]
@AirBorne04 Understand, did not consider that it would make sense to not 'respect' targetDeadline provided by pool ... however what would be the benefit ... less bandwidth? less pool requests? Both should be not a problem?! Due to very low anyway?

**Comment by AirBorne04** [comment]
As described in my situation the pool deadline was rather high and i wanted to prevent to send high dealines (as the pool was also rather slow at then), on the other hand i did not want to change the pool and from creepMiner i have seen that it is sending the minimum deadline from miner config and pool. But you are right at the end it does not make a huge difference i guess, i would just feel better not stressing the pool as "much".
