### ISSUE TITLE
send blockheight together with nonce params to pool

### ISSUE THREAD

**Issue by spebern** [de-luxe/burstcoin-jminer#53]
Hi, 

Is it possible to send the "blockheight" together with the other nonce parameters to the pool? It happens
that on fast blocks the block heights of miner and pool can be out of sync which leads to huge deadlines
on the side of the pool. Without a deadline limit it's impossible for the pool to evaluate if that might
have been a nonce submitted on the previous block.

On pools estimating the miner's plot size based on their deadlines this can lead to problems.
Creepminer already adds a parameter "blockheight" for this.

Thanks!

**Comment by de-luxe** [comment]
Thx! @spebern
