### ISSUE TITLE
Unable to get mining info from wallet

### ISSUE THREAD

**Issue by litasio** [de-luxe/burstcoin-jminer#56]
Hello, i'm stuck at this point, reading times are good, but miner drops after 10min of work to Unable to get mining info... Im mining on 1060 card, gpu. On BTFG pool.

https://ibb.co/gVcBsc

https://ibb.co/jAHakx

**Comment by de-luxe** [comment]
@litasio should be no issue, per default (refreshInterval) miner asks every 2 sec. for mining info (in your case every 500ms) ... even if it fails every 3rd time it should be no issue ... but sure the message can be annoying, i should solve it like blago with a kind of network quality indicator.

**Comment by litasio** [comment]
I found a solution, to run separate miner for each drive. Only way it works

**Comment by de-luxe** [comment]
@litasio once again, if getting mining info from pools fails 1 out of 10, it is no need to worry ... i don't suggest using multiple instances.

**Comment by litasio** [comment]
It is getting stuck, no matter what ms im entering. Doesnt start on block

**Comment by litasio** [comment]
I can provide teamviewer access if you can get it fixed. Not working for me, as hard i try

**Comment by de-luxe** [comment]
@litasio thanks for the offer, what system do you use? a mac? To look into that, i would need to debug on your system, setting that up could take a while.

**Comment by litasio** [comment]
PC

**Comment by de-luxe** [comment]
Hmm, any empty plotfiles in your plot directories? What java version do you use? In Windows i never heard of such a issue ...

**Comment by litasio** [comment]
Two guys from pool community tried also using teamviewer to set everything up and they gave up. Im on windows 10. Can you take a look?

**Comment by de-luxe** [comment]
@litasio sure, you can write a encrypted message to BURST-LUXE-RED2-G6JW-H4HG5 for teamviewer access data. Guess it is no good idea to post it here? Never used it, so don't know.

**Comment by de-luxe** [comment]
@litasio well however, should work now ... what we figured out  is, that jminer does not work with java9! I will do some additional testing on that.

**Comment by litasio** [comment]
Thank you very much! Ill get back if i face new issues.:)
