### ISSUE TITLE
Colors on dl confirmed

### ISSUE THREAD

**Issue by alpha13fr** [de-luxe/burstcoin-jminer#58]
Sorry to disturb.
First, nice work
Is it possible to have colors ( red or another) on line with dl  confirmed ?

Thx a lots
Delete this if you think it's not its place

**Comment by de-luxe** [comment]
@alpha13fr No, sorry ...  always had doing a GUI in mind, guess thats why i never thought about colors :)
If you are 'NOT using Windows' or 'use Windows with e.g. cygwin commandline', you can modify the logpattern like:
`logPatternConsole=%highlight(%d{HH:mm:ss}) | %boldYellow(%msg%n)`
source: https://logback.qos.ch/manual/layouts.html#coloring
But thats not exactly what you want i guess ... 

You also could reduce logs to the min, to see only confirms:
```
readProgressPerRound=0
showDriveInfo=false
showSkippedDeadlines=false
logPatternConsole=%d{HH:mm:ss} | %msg%n
walletServer=
```

**Comment by alpha13fr** [comment]
Thx for all
