### ISSUE TITLE
Unable to get mining info from wallet - Mac OSX 10.13.4 High Sierra

### ISSUE THREAD

**Issue by techboycr** [de-luxe/burstcoin-jminer#60]
I am having this issue right in the begining, but is hapenning for pool mining only:

`2018-04-18 20:03:55.772  WARN 21556 --- [cTaskExecutor-3] b.j.c.n.t.NetworkRequestMiningInfoTask   : Unable to get mining info from wallet.
`

But for solo mining is working correctly:
```
2018-04-18 20:10:45.183  INFO 21750 --- [cTaskExecutor-1] burstcoin.jminer.JMinerCommandLine       : START block '481144', scoopNumber '3849', capacity '0 GB'
2018-04-18 20:10:45.183  INFO 21750 --- [cTaskExecutor-1] burstcoin.jminer.JMinerCommandLine       :       targetDeadline '6048000', netDiff '359134', genSig '129101..'
2018-04-18 20:10:45.204  INFO 21750 --- [cTaskExecutor-2] burstcoin.jminer.JMinerCommandLine       :       winner block '481143', 'BURST-EXJ2-W6ZY-AWUW-A8ZDC'
```
I already try with all options localhost, 127.0.0.1, computer name all of that.

My java version is:

```
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
```
And this is my config file:
```

plotPaths=/Volumes/2Tb_HD/burst
scanPathsEveryRound=
listPlotFiles=

poolMining=false

targetDeadline=6048000
forceLocalTargetDeadline=
dynamicTargetDeadline=

numericAccountId=12791617055577555597687
poolServer=pool.burst4all.com:8124

# Winner
walletServer=http://localhost:8125
winnerRetriesOnAsync=
winnerRetryIntervalInMs=

soloServer=http://localhost:8125
passPhrase=then stun talk rock drove verse patience begun gun treat flash freak
triggerServer=
recommitDeadlines=

platformId=
deviceId=

refreshInterval=2000
updateMiningInfo=true
connectionTimeout=120000

debug=
writeLogFile=
logFilePath=
logPatternConsole=
logPatternFile=

readProgressPerRound=
byteUnitDecimal=
showDriveInfo=
showSkippedDeadlines=

chunkPartNonces=
readerThreads=
```

Thanks!!

**Comment by de-luxe** [comment]
@techboycr you need to use 'http://' for' poolServer' property like you did for walletServer
e.g. **poolServer=http://pool.burst4all.com:8124**

WARNING: you posted your 'passPhrase' above ... do not use that account anymore, create a new one and replot! Your passPhrase allows everyone to access you account, it is kind of your private key, the seed to your account ... never use it online, never post or give it to someone or once you have some burst, they will be lost!
