### ISSUE TITLE
Unable to parse mining info, received http status code 502

### ISSUE THREAD

**Issue by pvanmastrigt** [de-luxe/burstcoin-jminer#62]
Hi,

I am trying jminer version 0.4.12 for Burst mining on fastpool.info from an iMac. This seems to work well, however, an annoying and persistent error clogs the log file:

2018-05-11 20:31:23.045  WARN 13490 --- [skExecutor-9711] b.j.c.n.t.NetworkRequestMiningInfoTask   : Unable to parse mining info, received http status code 502
2018-05-11 20:31:23.045  WARN 13490 --- [skExecutor-9711] b.j.c.n.t.NetworkRequestMiningInfoTask   : Unable to parse mining info: <!DOCTYPE html>

Followed by several pages of errors. Then the mining continues. The messages are almost every round (but not always - some rounds have no error (1% or so).

I have seen this issue reported before, and considered solved. Appreciate any tip to resolve this.

With regards

**Comment by de-luxe** [comment]
@pvanmastrigt you could try to use another pool, as there may be connection issues from your location. http://www.checkupdown.com/status/E502.html

**Comment by pvanmastrigt** [comment]
Hello de-Luxe, thanks for your steer - I tried https://0-100pool.burstcoin.ro/ and seems to work without any problems. No errors detected, other than the plot size is not correctly reflected in the pool (underestimated by a factor 50). I'll stick with this pool for a while as the plot size appears to be corrected upward every round. With regards,
Piet

**Comment by de-luxe** [comment]
@pvanmastrigt guess it takes at least 24h for the pool to estimate your size more accurate. You may set
'dynamicTargetDeadline=true' while using pocc pool ... and jminer will use their formular
**targetDL = 720 * netDifficulty / yourPlotSize** for targetDeadline, explained under 'Quick Info' Tab on the pool website.
