### ISSUE TITLE
burstcoin jminer mining errors

### ISSUE THREAD

**Issue by leijameszhang** [de-luxe/burstcoin-jminer#63]
Anyone got similar issues when using jminer ? I didn't get those errors before until I restarted and re-plugin pc and hard disks.

Unable to get mining info from wallet: java.io.EOFException: HttpConnectionOverHTTP@951539c(l:/192.168.0.33:56971 <-> r:pool.burstmining.club/192.99.252.194:8124,closed=false)=>HttpChannelOverHTTP@4af0dcd8(exchange=HttpExchange@31deb94c req=TERMINATED/null@null res=PENDING/null@null)[send=HttpSenderOverHTTP@21e8791d(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator@22a6030f{s=START}],recv=HttpReceiverOverHTTP@6efc1d9f(rsp=IDLE,failure=null)[HttpParser{s=CLOSED,0 of -1}]]<-SocketChannelEndPoint@2aaccdd5{pool.burstmining.club/192.99.252.194:8124<->/192.168.0.33:56971,ISHUT,fill=-,flush=-,to=234/0}{io=0/0,kio=0,kro=1}->HttpConnectionOverHTTP@951539c(l:/192.168.0.33:56971 <-> r:pool.burstmining.club/192.99.252.194:8124,closed=false)=>HttpChannelOverHTTP@4af0dcd8(exchange=HttpExchange@31deb94c req=TERMINATED/null@null res=PENDING/null@null)[send=HttpSenderOverHTTP@21e8791d(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator@22a6030f{s=START}],recv=HttpReceiverOverHTTP@6efc1d9f(rsp=IDLE,failure=null)[HttpParser{s=CLOSED,0 of -1}]]

I tried online wallet and local wallet, both way having this issues. some posts say just ignor it. But really want to get rid of it if anyone can help.

Error: ReaderPartLoadedEvent for unknown chunkPartStartNonce: '2326435586'! Please check for plot-file duplicate or overlapping plots e.g. use https://bchain.info/BURST/tools/overlap

I'm for sure I don't have any duplicate or overlapping plots and I never got this errors before using same plots files until after I restarted my pc few weeks ago. BTW, seems cannot open the link https://bchain.info/BURST/tools/overlap.

Any comments/suggestions appreciated.

**Comment by de-luxe** [comment]
@leijameszhang yep https://bchain.info/BURST/tools/overlap is no longer available ... your error is a connection issue what may be caused by wrong settings in jminer.properties or a pool having issues etc.
Please check or post your poolServer, walletServer, soloServer settings. If thats ok, maybe try another pool.

**Comment by de-luxe** [comment]
@leijameszhang please reopen with more details if 0.5.2-RELEASE does not fix this issue.
