### ISSUE TITLE
Jminer for PoC2

### ISSUE THREAD

**Issue by ciscler** [de-luxe/burstcoin-jminer#64]
Hi all,
sorry for this post but I wanted to now if there will be an update of the jminer for the hardfork in mid june.

cheers

**Comment by de-luxe** [comment]
@ciscler No need to be sorry ... yes, i will release a first version soon. For now it will be able to already use POC2 plotfiles (together with POC1 plotfiles) .... even before the fork (double data needs to be read, to avoid too much drive seeks). I'm just testing it. So miners will be able to start converting their plotsfiles smoothly.

**Comment by ciscler** [comment]
Great thx for your good work. Really like jminer

**Comment by de-luxe** [comment]
https://github.com/de-luxe/burstcoin-jminer/releases/tag/0.5.0-SNAPSHOT
