### ISSUE TITLE
=)

### ISSUE THREAD

**Issue by JohnnyFFM** [de-luxe/burstcoin-jminer#66]
Hi Luxe,

re: LOG.info("   If you use JohnnyFFM/Poc1to2Converter you need to remove it manually.");

I just fixed this with the latest converter release. Was only the case if not converting inline. 

Best, Johnny

**Comment by de-luxe** [comment]
Thanks, i just wanted to avoid user support by pointing this out. Thanks for the xplotter updates btw.!
