### ISSUE TITLE
Possible issue in PlotFile.java

### ISSUE THREAD

**Issue by okaybmd** [de-luxe/burstcoin-jminer#69]
Hi!

I was looking through the code and I noticed this:

`... (chunkNumber * staggeramt + partNumber * (staggeramt / numberOfParts))`

in PlotFile.java file.

Aren't you supposed to do ` + (partNumber * (staggeramt / numberOfParts))` (add extra paranthesis)?

Cheers

**Comment by de-luxe** [comment]
@okaybmd first of all thanks for looking into it, guess you tried to fix the issue with 'Overlapping' ... will release a fix for that later today.
No the formular is fine, could even be
 (chunkNumber * staggeramt + partNumber * staggeramt / numberOfParts)
due multiplication and division operators have precedence over the addition and subtraction operators.
