### ISSUE TITLE
Not start

### ISSUE THREAD

**Issue by Psyhopath** [de-luxe/burstcoin-jminer#70]
Hi, when i instal jminer 0.5.2-RELEASE and confing jminer not starting

**Comment by de-luxe** [comment]
@Psyhopath i fear you need to provide some more info, in case you expect me to help you :-) e.g. post your config ... or run from command line and post the errors you get ...

**Comment by MALLICA666** [comment]
I ran into the same problem. The run.bat and the run.sh file has the incorrect settings.

**Comment by MALLICA666** [comment]
So I corrected both of the files and I am up and running now.

**Comment by MALLICA666** [comment]
java -jar -d64 -XX:+UseG1GC burstcoin-jminer-0.5.2-RELEASE.jar
Replace the commands with this one above.

**Comment by MALLICA666** [comment]
Let me know if that works for you.

**Comment by de-luxe** [comment]
@Psyhopath Sry was too late yesterday, should have found that one :-) Thank you for reporting! @MALLICA666 Thanks for helping out here.
I updated the 0.5.2-RELEASE with correct contents in run files.
