### ISSUE TITLE
listPlotFiles=true does not always show list

### ISSUE THREAD

**Issue by DefiantMiner** [de-luxe/burstcoin-jminer#73]
1.) Many times when the miner is started, it does not show a list of drives/plots when this setting is enabled.  Everything else seems to be working mining-wise, no errors, all converted POC2 files, no stagger in names, etc.

2.) I have noticed a significant decrease in processing speed now that plots are converted to POC2.  What used to take 15-18secs (43TB), now takes 25-30secs.  File sizes & number have not changed.  Same config as before except now on all POC2.  Is this due to us still being pre-fork at block ~502000?

**Comment by zodi1337** [comment]
Hi!
1.) Also see this Issue, but only on windows systems never on linux. What kind of OS you are use?

2.) Jep, it is due to the 2nd fork at block 502000. After this your roundtimes should be ok again.
For testing you can set "poc2ActivationBlockHeight=500000" (just a block in past), and your readtimes should be also ok. But just use it for a short test since your DL gonna not submitted!
I personally didn't tested it ;)

**Comment by ghost** [comment]
@DefiantMiner as per zodi1337 it will be more or less half the speed.
I did however notice that the conversion POC2->POC1 is indeed happening much slower than on OPENCL creepMiner or even Blagominer.
We should not however worry too much about it, as once we hit 502k block all the POC2 plots should be read much faster and everyone slowly will move to POC2 plots eventually.

**Comment by DefiantMiner** [comment]
Using Win10 1709, 32GB, 43.5TB, RX460.   Sounds like there's a listplotfiles bug with it on Windows.

Ah, figured but has no confirmation.  The speed reduction is not quite 50% so I was a little concerned with it...but I'll just let her run as is and see what happens after 502000.

Thanks, all.

**Comment by ghost** [comment]
@DefiantMiner I agree that the speed drop is more than 50%, but you should still send the deadlines. You can always move to Blago or CreepMiner until 502k. With RX460 I would personally use OPENCL version of CreepMiner which seems to be doing rather well with POC1<->POC2 conversion.

**Comment by DefiantMiner** [comment]
Oh it's sending deadlines just fine...I've actually forged 2 blocks during and after the POC2 convert.   Just a little slow on the cha-chunk'n.   Sounds like it's temporary so I'm fine with that.

I might play with CreepMiner OpenCL...but I'd rather not mess with more downtime unless required.  Maybe with one of the test systems...dunno.

**Comment by de-luxe** [comment]
@DefiantMiner thanks for reporting issue with listPlotFiles, strange that it is not deterministic ... will look into it. Poc2 using twice the time before 502000 is expected, as double the data gets read ... no issue there.

**Comment by DefiantMiner** [comment]
Copy that.  Thank you for your continued work and support on the miner.
