### ISSUE TITLE
Problem forwarding DL to Creepminer

### ISSUE THREAD

**Issue by Marko-Miner** [de-luxe/burstcoin-jminer#75]
Hello. I have a Problem with forwarding the DL to Creepminer. Jminer send the DL, but they are not confirmed and i not see the sended DL in Creepminer.

Creepminer 1.8.2
Jminer last Release 0.5.2

with an older Jminer version i see the DL in Creepminer 

can you help me please….?

I use Jminer Long time and have never a Problem before

Thanks for helping

**Comment by de-luxe** [comment]
@Marko-Miner What jminer version did you use before 0.5.x ? As the latest changes to submitNonce were made in 0.4.12 version, if that did work ... i'm not sure what could cause the issue. Maybe @Creepsky can take a look and provide info what would be needed by creepMiner in https://github.com/de-luxe/burstcoin-jminer/blob/master/src/main/java/burstcoin/jminer/core/network/task/NetworkSubmitPoolNonceTask.java#L124

**Comment by Marko-Miner** [comment]
i have solved the Problem.
is not from Jminer… the Problem is in the last release of creepminer

in creepminer 1.7.19.0 was the solution :
 "calculateEveryDeadline" : false,
 for me was this the solution
 now my miner run good. and forwarding go
 but before i have the same Problem

but only work with creepminer 1.7.19.0
