### ISSUE TITLE
Showing incorrect memory size of graphic card

### ISSUE THREAD

**Issue by MALLICA666** [de-luxe/burstcoin-jminer#77]
burstcoin-jminer-0.5.2-RELEASE
the older jminer version use to.
It used to show the correct size of the memory.
My graphic card memory size is 2GB of memory. Now it is showing 7GB of memory.
May not be important but was something to say incase it is.

**Comment by de-luxe** [comment]
@MALLICA666 My only test was, if my GPU was reported correctly ... however, it has no influence at all, mainly it is just, so that you can identify a card within your system. To ensure your platform/device settings are correct.
